# Nexus Web UI
# 特殊配置：大构件上传 + 关闭缓冲
server {
    listen 80;
    server_name nexus.renew.com;

    client_max_body_size 500m;
    proxy_buffering off;

    location / {
        proxy_pass http://${NEXUS_HOST}:${NEXUS_HTTP_PORT};
        include /etc/nginx/proxy_params;
    }
}
