# Apollo Portal — 非生产独有（③ 类域名，全局唯一 Portal）
# 访问：http://apollo.renew.com → 默认账号 apollo/admin
server {
    listen 80;
    server_name apollo.renew.com;
    location / {
        proxy_pass http://${APOLLO_HOST}:${APOLLO_PORTAL_PORT};
        include /etc/nginx/proxy_params;
    }
}
